In [ ]:
# Install a specific version of the package(Pandas-profiling)
import pandas as pd
import pandas_profiling

In [ ]:
# Make sure to load the file( ListA.txt) to your Colab notebook
df_list_a = pd.read_csv("/content/sample_data/ListA.txt", sep= '\t')

In [ ]:
# Display the top 10 records of the dataset
df_list_a .head(10)

,recid,fname,lname,mname,address,city,state,zip,ssn,homephone
0,A848132,A,HYRE,NICHOLE,4749 audrey dr,winston salem,nc,27127.0,337-80-1789,(834)-289-5647
1,A848133,NaN,HONDROS,K,1225 WATSON AVE,WINSTON SALEM,NC,27103.0,NaN,(541)7124583
2,A848134,KENNETH,CORBIN,LEROY,2426 E ONYX TRL APT 3,FAYETTEVILLE,AR,72701.0,732-38-4668,(415)-796-3891
3,A848135,NaN,FREIDA,NaN,625 RUNNINGBROOK LN,RURAL HALL,NC,27045.0,591-12-8339,(816)-465-1843
4,A848136,NaN,FLEMING,G,14272 HOOVER ST TRLR 38,WESTMINSTER,CA,92683.0,910-46-5484,(267)-284-9321
5,A848137,JORY,HARRELL,NaN,1620 TRINITY GARDEN CIR,CLEMMONS,NC,27012.0,NaN,(327)-137-1374
6,A848138,B,GORDON,MCCOY,5205 MERELEDGE CT # J,WINSTON SALEM,NC,27106.0,164-79-2690,(179)-461-1587
7,A848139,Twanna,Fuller,Denise,434 VALLEYMEADE DR,KERNERSVILLE,NC,27284.0,477-68-9404,(936)-795-6148
8,A848140,CLAUDE,KENNEDY,R,1763 LATONIA RD,WINSTON SALEM,NC,27127.0,406-74-2780,(948)-154-8735
9,A848141,MARY,DULA,ELIZABETH,5412 MESA CT,WINSTON SALEM,NC,27106.0,342768316,(925)-872-9356

In [ ]:
# Display the last 10 records of the dataset
df_list_a .tail(10)

,recid,fname,lname,mname,address,city,state,zip,ssn,homephone
151858,A999990,BRENDA,JACKSON,NaN,1317 E SECOND ST,WINSTON SALEM,NC,27101.0,435-41-4611,(258)-721-8679
151859,A999991,TANIA,BROWN,SHICOLE,129 W LEMLY ST,WINSTON SALEM,NC,27127.0,274371229,(794)-378-8267
151860,A999992,NaN,HAUSER,A,319 S MAIN ST,WINSTON SALEM,NC,27101.0,218-44-5236,(285)-617-1468
151861,A999993,TIMOTHY,HUNSUCKER,W,215 GRANDVIEW DR,WINSTON SALEM,NC,27104.0,466-77-5602,(263)-291-6179
151862,A999994,NaN,HOLCOMB,ALVIN,195 WILLOW BEND CT # J,KERNERSVILLE,NC,27284.0,421-21-5062,(541)-623-8679
151863,A999995,KERRIN,JARRELL,LURAE,1664 RIDGESTONE LN,KERNERSVILLE,NC,27284.0,468-82-9029,(764)-672-8719
151864,A999996,BRANDON,AMBROSE,HEATH,5280 CAMP BETTY HASTINGS RD,WALKERTOWN,NC,27051.0,995797604,NaN
151865,A999997,NaN,CLINARD,SHAWN,4777 VIENNA DOZIER RD,PFAFFTOWN,NC,27040.0,115517807,578-974-1578
151866,A999998,JAMES,ALLISON,GERALD,1305 WOODLYN ST,KERNERSVILLE,NC,27284.0,539-35-7671,NaN
151867,A999999,ROBERT,BUYNA,NaN,6508 lagrande place dr # 4,lewisville,nc,27023.0,558-62-1059,NaN

In [ ]:
# What is the shape of the dataset - Total rows and columns
df_list_a .shape

(151868, 10)

In [ ]:
# Select records(rows) from “AR” which are having “fname” and “ssn” not missing/not blank
df_list_a[(df_list_a.state=="AR")&(df_list_a.fname.notnull())&(df_list_a.ssn.notnull())]

,recid,fname,lname,mname,address,city,state,zip,ssn,homephone
2,A848134,KENNETH,CORBIN,LEROY,2426 E ONYX TRL APT 3,FAYETTEVILLE,AR,72701.0,732-38-4668,(415)-796-3891
187,A848319,Steven,Jolly,Lamont,131 MILLBROOK ST,PEARCY,AR,71964.0,148-91-5787,(159)-713-3512
607,A848739,RACHEL,BYYRD,NaN,510 QUAIL ST,ASHDOWN,AR,71822.0,450-17-1817,(864)-867-4632
762,A848894,ANNIE,BRADLEY,MAE,1650 GREENE ROAD 847,PARAGOULD,AR,72450.0,999-99-4948,(934)-756-2438
1187,A849319,James,Campbell,NaN,1501 NE DYSART WOODS LN,BENTONVILLE,AR,72712.0,938-95-8782,(358)-581-7362
...,...,...,...,...,...,...,...,...,...,...
150590,A998722,MICHAEL,KETTERING,D,2810 LOVE CREEK DR,TEXARKANA,AR,71854.0,629-64-5354,741-486-2136
151419,A999551,Sarah,Caroway,Callahan,348 BRADLEY 33 RD,WARREN,AR,71671.0,113-41-4019,(982)8658241
151420,A999552,JOONATHAN,HAYNES,RAY,425 POLK ROAD 136,COVE,AR,71937.0,402-64-1045,(973)-485-5472
151570,A999702,BRUCE,CARTER,NaN,25 ROLLING LN,LITTLE ROCK,AR,72209.0,537-20-4290,(214)-732-7248
151843,A999975,STEVEN,GLEDHILL,FRED,267 GILMER LN,HOT SPRINGS NATIONAL PARK,AR,71901.0,441-75-4546,(728)6934571

In [ ]:
# Sort records(row) by “fname”
df_list_a.sort_values(['fname'], ascending=True)

,recid,fname,lname,mname,address,city,state,zip,ssn,homephone
0,A848132,A,HYRE,NICHOLE,4749 audrey dr,winston salem,nc,27127.0,337-80-1789,(834)-289-5647
116075,A964207,A,HONEY,CON,3482 TANGLEBROOK TRL,CLEMMONS,NC,27012.0,NaN,(267)-192-1497
32092,A880224,A,GWYN,NaN,4420 KIMBALL LN,WINSTON SALEM,NC,27105.0,466714957,(416)-647-5341
56244,A904376,A,HOBACK,MAE,107 DILLON ST,WINSTON SALEM,NC,27107.0,369-57-2984,NaN
80344,A928476,A,CERECERES,MARCUS,813 CROOKED RUN RD,RURAL HALL,NC,27045.0,426-27-9547,(913)-729-9172
...,...,...,...,...,...,...,...,...,...,...
151852,A999984,NaN,JONES,M,5060 LAKE GARDEN CT,KERNERSVILLE,NC,27284.0,841-61-9155,(653)-483-6372
151856,A999988,NaN,JONES,W,3534 FIELDSTONE DR,WINSTON SALEM,NC,27105.0,NaN,(895)-371-3452
151860,A999992,NaN,HAUSER,A,319 S MAIN ST,WINSTON SALEM,NC,27101.0,218-44-5236,(285)-617-1468
151862,A999994,NaN,HOLCOMB,ALVIN,195 WILLOW BEND CT # J,KERNERSVILLE,NC,27284.0,421-21-5062,(541)-623-8679
151865,A999997,NaN,CLINARD,SHAWN,4777 VIENNA DOZIER RD,PFAFFTOWN,NC,27040.0,115517807,578-974-1578

In [ ]:
# Generate the profiling report
profile_list_a = pandas_profiling.ProfileReport(df_list_a)
profile_list_a

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# Save as an html file. The file should be in the Files section on Colab.
profile_list_a.to_file('list_a.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]